//! Execution Plane types for signature orchestration.
//!
//! These types define the data boundary between the Control Plane
//! and the Execution Plane. The Control Plane constructs a `SignatureRequest`
//! from a finalized, approved transaction artifact. The Execution Plane
//! returns a `SignatureOutcome` or `SignatureError`.
//!
//! # What belongs here
//!
//! Only types needed by the wallet layer to route, sign, and track requests.
//!
//! # What must NOT be here
//!
//! PolicyVerdict, SimulationResult, ApprovalMode, or any Control Plane artifact.
//! Base64 encoding or other transport-layer concerns.
//! Audit, spend, or event types.

use std::fmt;

use solana_sdk::pubkey::Pubkey;
use uuid::Uuid;

use claw_types::session::SessionId;

// ── SignatureRequestId ──────────────────────────────────────────────────────

/// Execution Plane only.
/// Opaque identifier for a signature request tracked by the orchestrator.
///
/// Wraps a UUID. Used as the correlation key between `submit()` and `complete()`.
/// Must NOT be reused across requests. Generated by the caller before submitting.
///
/// The orchestrator rejects duplicate IDs (fail-closed).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct SignatureRequestId(pub Uuid);

impl SignatureRequestId {
    /// Creates a new, random request ID.
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }
}

impl Default for SignatureRequestId {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for SignatureRequestId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(f)
    }
}

impl From<Uuid> for SignatureRequestId {
    fn from(uuid: Uuid) -> Self {
        Self(uuid)
    }
}

// ── SignatureRequest ────────────────────────────────────────────────────────

/// Execution Plane only.
/// The input artifact for signature orchestration.
///
/// Constructed by the caller (Control Plane) from a finalized, approved transaction.
/// Contains only what the Execution Plane needs to route and sign.
///
/// # Must NOT contain
///
/// - `PolicyVerdict`, `SimulationResult`, `ApprovalMode` (Control Plane artifacts)
/// - `fee_lamports` or spend-related data (caller's responsibility)
/// - Any field that would require the wallet layer to interpret business meaning
///
/// # Invariants relied upon by the wallet layer
///
/// - `finalized_tx_bytes` is a valid bincode-serialized `solana_sdk::transaction::Transaction`
/// - That transaction has compute budget instructions prepended and a fresh blockhash set
/// - The transaction has already passed simulation and policy evaluation upstream
/// - `expected_signer` is a pubkey that appears in the transaction's `account_keys`
pub struct SignatureRequest {
    /// Unique identifier for this request. Generated by the caller.
    /// The orchestrator rejects duplicate IDs.
    pub id: SignatureRequestId,

    /// Session that originated this request.
    /// Used by adapters for routing decisions (e.g., session-wallet binding lookup).
    pub session_id: SessionId,

    /// Upstream transaction identifier (the proposal's UUID).
    /// Carried through for the caller's audit/event correlation.
    /// The orchestrator does not interpret this value.
    pub transaction_id: Uuid,

    /// Bincode-serialized finalized unsigned Transaction.
    /// These are the exact bytes the wallet adapter must sign.
    /// No adapter may modify these bytes before signing.
    pub finalized_tx_bytes: Vec<u8>,

    /// The public key expected to produce the signature.
    /// Used by adapters for routing (`supports()`) and by the external
    /// adapter for verification (did the correct key sign?).
    pub expected_signer: Pubkey,

    /// Human-readable description of the transaction.
    /// Used only for pending request listing. The orchestrator and adapters
    /// do not interpret this value.
    pub description: String,
}

// ── SignatureOutcome ────────────────────────────────────────────────────────

/// Execution Plane only.
/// The result of a successful signature orchestration operation.
///
/// Returned by `SignatureOrchestrator::submit()` and `SignatureOrchestrator::complete()`.
/// The caller is responsible for all downstream effects (audit, spend, events)
/// based on the variant received.
///
/// # Must NOT contain
///
/// - Control Plane artifacts (`PolicyVerdict`, `SimulationResult`)
/// - Transport-layer encoding (base64). Carries raw bytes only.
///   Encoding for HTTP/JSON is the caller's responsibility.
#[derive(Debug)]
pub enum SignatureOutcome {
    /// Signing completed synchronously.
    /// Returned by local adapters that sign immediately.
    /// The caller should record the signature in audit and emit `TransactionSigned`.
    Signed {
        /// The request this outcome corresponds to.
        request_id: SignatureRequestId,
        /// The on-chain signature string (base58-encoded by Solana SDK).
        signature: String,
        /// Bincode-serialized signed Transaction.
        /// The caller may need this for RPC submission.
        signed_tx_bytes: Vec<u8>,
        /// Which adapter produced this signature (e.g., "local", "external").
        adapter_type: String,
        /// Upstream transaction identifier from the consumed SignatureRequest.
        /// Carried through for the caller's audit/event correlation.
        transaction_id: Uuid,
        /// The pubkey that produced the signature (string form for audit/events).
        expected_signer: String,
    },

    /// Request accepted but signing is asynchronous.
    /// Returned by external adapters (Phantom, Ledger) that require out-of-band signing.
    ///
    /// The caller should emit `WalletSignatureRequested` and return the unsigned tx
    /// to the user. The caller must later call `orchestrator.complete()` when the
    /// signed payload arrives.
    ///
    /// The caller is responsible for encoding `finalized_tx_bytes` to base64
    /// (or other transport format) before sending to the client.
    Pending {
        /// The request this outcome corresponds to.
        request_id: SignatureRequestId,
        /// Which adapter is handling this request (e.g., "external").
        adapter_type: String,
        /// Raw finalized unsigned transaction bytes (bincode-serialized).
        /// The caller encodes these for transport (e.g., base64 for HTTP responses).
        finalized_tx_bytes: Vec<u8>,
    },
}

// ── SignatureError ──────────────────────────────────────────────────────────

/// Execution Plane only.
/// Errors from signature orchestration operations.
///
/// The caller is responsible for translating these into audit events,
/// HTTP responses, or tool error outputs. The orchestrator does not
/// perform any side effects on error.
///
/// # Must NOT contain
///
/// Control Plane error variants (policy blocked, approval denied).
#[derive(Debug)]
pub enum SignatureError {
    /// No registered adapter supports this request.
    /// The caller should check session-wallet bindings or keystore state.
    NoAdapter,

    /// A request with this ID is already tracked in the pending map.
    /// The caller must use a unique `SignatureRequestId` per request.
    /// This error indicates a caller bug (ID reuse).
    DuplicateRequestId,

    /// The adapter attempted signing but the cryptographic operation failed.
    /// Contains the underlying error message from the signer.
    SigningFailed(String),

    /// The externally-signed transaction failed verification.
    /// Contains the reason (message mismatch, signer not found, invalid signature, etc.).
    ///
    /// The pending request has been consumed (removed from the pending map).
    /// A retry requires a new `SignatureRequest` from the Control Plane.
    VerificationFailed(String),

    /// The external wallet modified the transaction's `recent_blockhash`.
    ///
    /// In strict V0 mode (the default), Claw approves a specific JIT-built artifact.
    /// Allowing the wallet to change the blockhash would let an external party alter
    /// the effective validity window of an approved transaction without re-approval.
    /// In V0+ALT contexts the blockhash also anchors the ALT resolution slot.
    ///
    /// This error is a **retry signal**: the caller should trigger a fresh JIT build
    /// from the original `SwapIntent` and re-send the new tx for signing.
    /// The pending entry has been consumed (same as `VerificationFailed`).
    BlockhashModified,

    /// No pending request exists with this ID.
    /// Either the request was already completed, expired, or never existed.
    /// The orchestrator is pending-only: completed requests are not retained.
    RequestNotFound,

    /// The `finalized_tx_bytes` could not be deserialized into a Transaction.
    /// Indicates a bug in the caller's serialization or corrupted data.
    InvalidTransaction(String),
}

impl fmt::Display for SignatureError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::NoAdapter => write!(f, "no wallet adapter supports this request"),
            Self::DuplicateRequestId => write!(f, "duplicate signature request ID"),
            Self::SigningFailed(e) => write!(f, "signing failed: {e}"),
            Self::VerificationFailed(e) => write!(f, "verification failed: {e}"),
            Self::RequestNotFound => write!(f, "no pending request with this ID"),
            Self::InvalidTransaction(e) => write!(f, "invalid transaction bytes: {e}"),
            Self::BlockhashModified => write!(
                f,
                "wallet modified blockhash; rebuild required — \
                 resubmit a fresh JIT build from the approved intent"
            ),
        }
    }
}

impl std::error::Error for SignatureError {}

// ── PendingSummary ─────────────────────────────────────────────────────────

/// Execution Plane only.
/// Read-only summary of a pending signature request.
///
/// Returned by `SignatureOrchestrator::pending_for_session()`.
/// Contains no mutable handles or internal state.
/// The caller uses this for HTTP API responses (e.g., `GET /wallet-signatures`).
///
/// # Must NOT contain
///
/// - `std::time::Instant` or other non-serializable types
/// - Transport-encoded data (base64). Carries raw bytes only.
///   The API layer is responsible for encoding.
pub struct PendingSummary {
    /// Request identifier.
    pub request_id: SignatureRequestId,
    /// Upstream transaction identifier for correlation.
    pub transaction_id: Uuid,
    /// Which adapter is handling this (e.g., "external").
    pub adapter_type: String,
    /// Human-readable description.
    pub description: String,
    /// Expected signer pubkey (string form for API responses).
    pub expected_signer: String,
    /// Raw finalized unsigned transaction bytes.
    /// The API layer encodes to base64 for HTTP responses.
    pub finalized_tx_bytes: Vec<u8>,
}
